openapi: 3.0.0
info:
  title: User API
  description: API for user management including user creation, login, and verification.
  version: 1.0.0
servers:
  - url: http://{host}:{port}/api/v1
    description: Local environment
    variables:
      host:
        default: localhost
      port:
        default: 8080
paths:
  /user:
    post:
      summary: Create a new user
      description: Endpoint to create a new user account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: user
                email:
                  type: string
                  example: user@email.com
                password:
                  type: string
                  example: securepassword
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  username:
                    type: string
                  email:
                    type: string
        '400':
          description: Bad Request
  /login:
    post:
      summary: Log in to the system
      description: Endpoint to log in an existing user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: user
                password:
                  type: string
                  example: securepassword
      responses:
        '200':
          description: Successfully logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        '401':
          description: Unauthorized - Invalid credentials
  /user:
    get:
      summary: Get user details
      description: Retrieve the details of the authenticated user
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            example: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
      responses:
        '200':
          description: Successfully retrieved user details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  username:
                    type: string
                  email:
                    type: string
        '401':
          description: Unauthorized - Invalid or expired token
